#!/usr/bin/env python3
"""
Data-plane-equivalent accuracy verifier.

The P4 code generated by 5_generating_p4_code.py mirrors this offline
pipeline exactly: same canonical 5-tuple, same CRC-indexed register
arrays, same quantised PCA surrogate DTR (emitted as range-match P4
entries), same DT classifier (also emitted as range-match P4 entries).

The PCA-quantised codes that the BMv2 data plane produces for each flow
are byte-identical to the codes saved in tables/transform_mapping.csv,
so running the trained DT classifier on those codes gives the same
predictions a BMv2 deployment would produce — within the small
hash-collision delta that the offline extractor already simulates.

Usage (run from control_plane/, after steps 1-3 have been completed):

    python3 verify_accuracy.py
"""

import os
import pickle
import sys

import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TABLES_DIR = os.path.join(SCRIPT_DIR, 'tables')
MODEL_DIR  = os.path.join(SCRIPT_DIR, 'model')


def main():
    mapping_path = os.path.join(TABLES_DIR, 'transform_mapping.csv')
    dt_path      = os.path.join(MODEL_DIR,  'dt.model')

    if not os.path.exists(mapping_path):
        print(f"ERROR: {mapping_path} missing — run step 2 first.")
        sys.exit(1)
    if not os.path.exists(dt_path):
        print(f"ERROR: {dt_path} missing — run step 3 -m dt first.")
        sys.exit(1)

    df = pd.read_csv(mapping_path)
    if 'Label' not in df.columns:
        print("ERROR: transform_mapping.csv has no Label column.")
        sys.exit(1)

    feature_cols = [c for c in df.columns
                    if c != 'Label' and not c.endswith('_float')]
    X = df[feature_cols].values
    y = df['Label'].values

    with open(dt_path, 'rb') as f:
        dt_model = pickle.load(f)

    y_pred = dt_model.predict(X)

    print(f"Pipeline: PCA(k={len(feature_cols)}) + DT")
    print(f"Feature columns: {feature_cols}\n")

    # Per-class
    print("="*70)
    print(f"{'Class':16s}  {'Flows':>7s}  {'Correct':>8s}  {'Accuracy':>10s}")
    print("="*70)
    classes = sorted(set(y))
    for cls in classes:
        mask = (y == cls)
        total = int(mask.sum())
        correct = int(((y_pred == y) & mask).sum())
        print(f"{cls:16s}  {total:>7d}  {correct:>8d}  {correct/total*100:>9.2f}%")
    print("="*70)

    correct_overall = int((y_pred == y).sum())
    total_overall = len(y)
    overall = correct_overall / total_overall
    print(f"Overall accuracy: {overall*100:.2f}%  ({correct_overall}/{total_overall})")
    print(f"Target: >= 97.00%")
    print(f"Result: {'PASS' if overall >= 0.97 else 'FAIL'}\n")

    print("Detailed report (precision / recall / F1):")
    print(classification_report(y, y_pred, digits=4, zero_division=0))

    print("Confusion matrix (rows = true, columns = predicted):")
    cm = confusion_matrix(y, y_pred, labels=classes)
    header = "          " + "  ".join(f"{c[:8]:>8s}" for c in classes)
    print(header)
    for cls, row in zip(classes, cm):
        print(f"{cls[:8]:>8s}  " + "  ".join(f"{v:>8d}" for v in row))


if __name__ == '__main__':
    main()
